<?php

$this->setup(array(
    'title' => 'Cancel this booking',
    'panel' => 'centered-panel',
    'back' => true,
));

?>

<script type="text/javascript">
function showHide() {
   var div = document.getElementById('hidden_div');
   if (div.style.display == 'none') {
      div.style = 'position:fixed; top:0; right:0; bottom:0; left:0; background-color: rgba(0,0,0,0.5); z-index: 9999; display:flex; align-items:center; justify-content:center;';
      div.innerHTML = '<div style="text-align:center;color:#fff"><div class="spinner-border text-light mb-3" role="status"></div><div><?= $this->t('Processing cancellation ...') ?></div></div>';
   }
   else {
      div.style.display = 'none';
   }
}
</script>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to cancel this booking?') ?></span></p>

    <p class="no-wrap">
        <form method="post" action="<?= $this->url('square/booking/cancellation', [], ['query' => ['bid' => $this->bid]]) ?>" style="display:inline" onsubmit="showHide();">
            <input type="hidden" name="confirmed" value="true">
            <button type="submit" class="default-button" id="cancel-button">
                <span class="symbolic symbolic-cross"><?= $this->t('Yes, cancel this booking') ?></span>
            </button>
        </form>

        &nbsp;

        <a href="<?= $this->origin ?>" class="default-button squarebox-close-link"><?= $this->t('No, go back') ?></a>
    </p>
</div>

<div id="hidden_div" style="display:none" aria-busy="true">
</div>
