<?php

$this->setup(array(
    'title' => 'Cancel this booking',
    'panel' => 'centered-panel',
    'back' => array('Booking-Administration' => $this->url('backend/booking')),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this booking?') ?></span></p>

    <div class="edit-actions">
        <?php if ($this->sessionUser->can('admin.all')): ?>
            <a href="<?= $this->url('backend/booking/delete', ['rid' => $this->rid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button default-button-danger">
                <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this booking') ?></span>
            </a>
        <?php endif; ?>

        <a href="<?= $this->url('backend/booking/delete', ['rid' => $this->rid], ['query' => ['confirmed' => 'true', 'cancel' => 'true']]) ?>" class="default-button default-button-danger">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, cancel this booking') ?></span>
        </a>

        <a href="<?= $this->url('frontend') ?>" class="default-button default-button-outline squarebox-close-link"><?= $this->t('No, go back') ?></a>
    </div>

    <p class="small-text gray mt-3">
        <?= $this->t('If this booking is cancelled, it will disappear from the calendar, but remain in the database.') ?>
    </p>
</div>
