<?php

$this->setup(array(
    'title' => 'Cancel this reservation',
    'panel' => 'centered-panel',
    'back' => true
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to cancel or delete this reservation?') ?></span></p>

    <div class="edit-actions">
        <?php if ($this->sessionUser->can('admin.all')): ?>
            <form method="post" action="<?= $this->url('backend/booking/delete', ['rid' => $this->rid], ['query' => ['edit-mode' => 'reservation']]) ?>" style="display:inline">
                <?= $this->csrfToken() ?>
                <input type="hidden" name="confirmed" value="true">
                <button type="submit" class="default-button default-button-danger">
                    <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this reservation') ?></span>
                </button>
            </form>
        <?php endif; ?>

        <form method="post" action="<?= $this->url('backend/booking/delete', ['rid' => $this->rid], ['query' => ['edit-mode' => 'reservation']]) ?>" style="display:inline">
            <?= $this->csrfToken() ?>
            <input type="hidden" name="confirmed" value="true">
            <input type="hidden" name="cancel" value="true">
            <button type="submit" class="default-button default-button-danger">
                <span class="symbolic symbolic-cross"><?= $this->t('Yes, cancel this reservation') ?></span>
            </button>
        </form>

        <a href="<?= $this->url('frontend') ?>" class="default-button default-button-outline squarebox-close-link"><?= $this->t('No, go back') ?></a>
    </div>

    <p class="small-text gray mt-3">
        <?= $this->t('The booking itself will not be changed. Only the reservation at this date will be affected.') ?>
        <?= $this->t('If cancelled, it will disappear from the calendar but remain in the database.') ?>
    </p>
</div>
