<?php

$this->setup(array(
    'title' => 'Booking-Administration',
    'panel' => 'centered-panel',
    'back' => true,
));

?>

<div class="py-3">
    <p><?= $this->t('Change the time range of all unmodified reservations of this booking:') ?></p>

    <div class="sandbox mb-4">
        <?php

        $form = $this->editTimeRangeForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('backend/booking/edit/range', ['bid' => $this->booking->need('bid')], ['query' => ['mode' => 'time']]));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <div class="row align-items-end">
            <div class="col-sm-4">
                <?= $this->formRowCompact($form, 'bf-time-start') ?>
            </div>
            <div class="col-sm-4">
                <?= $this->formRowCompact($form, 'bf-time-end') ?>
            </div>
            <div class="col-sm-4">
                <div class="mb-2">
                    <?= $this->formElement($form->get('bf-submit')) ?>
                </div>
            </div>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>

    <p><?= $this->t('Change the date range and/or interval of this booking:') ?></p>

    <div class="sandbox">
        <?php

        $form = $this->editDateRangeForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('backend/booking/edit/range', ['bid' => $this->booking->need('bid')], ['query' => ['mode' => 'date']]));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <div class="row align-items-end">
            <div class="col-sm-4">
                <?= $this->formRowCompact($form, 'bf-date-start') ?>
            </div>
            <div class="col-sm-4">
                <?= $this->formRowCompact($form, 'bf-date-end') ?>
            </div>
            <div class="col-sm-4">
                <?= $this->formRowCompact($form, 'bf-repeat') ?>
            </div>
        </div>

        <div class="mt-3">
            <?= $this->formElement($form->get('bf-submit')) ?>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>
</div>

<?= $this->ajaxAwareScript('js/controller/backend/booking/edit-range.min.js') ?>
