<?php

$this->setup(array(
    'title' => 'Player\'s names',
    'panel' => 'centered-panel large-sized',
    'back' => true,
));

?>

<div>
    <h1><?= $this->t('Player\'s names') ?></h1>

    <div class="separator-small"></div>

    <p>
        <?= $this->translate('Booked by') ?>
        <a href="<?= $this->url('backend/user/edit', ['uid' => $this->user->need('uid')]) ?>"><?= $this->escapeHtml($this->user->need('alias')) ?></a>
    </p>

    <div class="separator separator-line"></div>

    <table class="table table-sm align-middle">
        <thead>
            <tr>
                <th style="width: 2rem;">#</th>
                <th><?= $this->t('Name') ?></th>
                <th><?= $this->t('Email') ?></th>
                <th><?= $this->t('Phone') ?></th>
                <th><?= $this->t('Matched user') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php $i = 1; foreach ($this->players as $player): ?>
                <tr>
                    <td><?= $i++ ?>.</td>
                    <td><?= isset($player['name']) ? $this->escapeHtml($player['name']) : '' ?></td>
                    <td>
                        <?php if (isset($player['email'])): ?>
                            <a href="mailto:<?= $this->escapeHtml($player['email']) ?>"><?= $this->escapeHtml($player['email']) ?></a>
                        <?php endif; ?>
                    </td>
                    <td><?= isset($player['phone']) ? $this->escapeHtml($player['phone']) : '' ?></td>
                    <td>
                        <?php if (isset($player['user']) && isset($player['userMatch'])): ?>
                            <span class="text-muted"><?= $this->translate('User matched by') ?> <?= $this->translate(ucfirst($player['userMatch'])) ?>:</span>
                            <a href="<?= $this->url('backend/user/edit', ['uid' => $player['user']->need('uid')]) ?>"><?= $this->escapeHtml($player['user']->need('alias')) ?></a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
