services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    volumes:
      - ./tmp/mail:/maildir
    networks:
      - courtnet

  mariadb:
    image: mariadb:10.11
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - courtnet

  court:
    image: court
    build:
      dockerfile: Dockerfile
      args:
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    restart: always
    volumes:
      - ./:/var/www/html
    depends_on:
      mailhog:
        condition: service_started
      mariadb:
        condition: service_healthy
    networks:
      - courtnet
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"

      # Secure Header Middleware
      - "traefik.http.middlewares.secure-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.court.middlewares=secure-headers"

      # HTTP -> HTTPS Redirect
      - "traefik.http.routers.court-redirect.entrypoints=web"
      - "traefik.http.routers.court-redirect.rule=Host(`${APP_HOSTNAME}`)"
      - "traefik.http.routers.court-redirect.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # HTTPS Router
      - "traefik.http.routers.court.rule=Host(`${APP_HOSTNAME}`)"
      - "traefik.http.routers.court.entrypoints=websecure"
      - "traefik.http.routers.court.tls=true"
      - "traefik.http.routers.court.tls.certresolver=myresolver"
      - "traefik.http.services.court.loadbalancer.server.port=80"

networks:
  courtnet:
    driver: bridge
  traefik_web:
    external: true