services:
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - ${MAILHOG_SMTP_PORT}:1025
      - ${MAILHOG_UI_PORT}:8025
    volumes:
      - ./tmp/mail:/maildir

  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/mysql

  court:
    build:
      dockerfile: Dockerfile
      args:
        INSTALL_XDEBUG: ${INSTALL_XDEBUG}
    restart: always
    ports:
      - ${COURT_PORT}:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - mailhog
      - mariadb
