<?php

$eid = $this->event->need('eid');

$backUrl = $this->url('backend/event/edit', ['eid' => $eid]);

$this->setup(array(
    'title' => 'Delete this event',
    'panel' => 'centered-panel',
    'back' => array(
        'Event' => $backUrl,
    ),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this event?') ?></span></p>

    <div class="edit-actions">
        <a href="<?= $this->url('backend/event/delete', ['eid' => $eid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button default-button-danger">
            <span class="symbolic symbolic-cross"><?= $this->t('Delete this event') ?></span>
        </a>

        <?php if (! empty($this->groupId)): ?>
            <a href="<?= $this->url('backend/event/delete', ['eid' => $eid], ['query' => ['confirmed' => 'true', 'group' => 'true']]) ?>" class="default-button default-button-danger">
                <span class="symbolic symbolic-cross"><?= $this->t('Delete entire series') ?></span>
            </a>
        <?php endif; ?>

        <a href="<?= $backUrl ?>" class="default-button default-button-outline"><?= $this->t('No, go back') ?></a>
    </div>
</div>
