<?php

$eid = $this->event->need('eid');

$backUrl = $this->url('backend/event/edit', ['eid' => $eid]);

$this->setup(array(
    'title' => 'Delete this event',
    'panel' => 'centered-panel',
    'back' => array(
        'Event' => $backUrl,
    ),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this event?') ?></span></p>

    <div class="edit-actions">
        <form method="post" action="<?= $this->url('backend/event/delete', ['eid' => $eid]) ?>" style="display: inline;">
            <?= $this->csrfToken() ?>
            <input type="hidden" name="confirmed" value="true">
            <button type="submit" class="default-button default-button-danger">
                <span class="symbolic symbolic-cross"><?= $this->t('Delete this event') ?></span>
            </button>
        </form>

        <?php if (! empty($this->groupId)): ?>
            <form method="post" action="<?= $this->url('backend/event/delete', ['eid' => $eid]) ?>" style="display: inline;">
                <?= $this->csrfToken() ?>
                <input type="hidden" name="confirmed" value="true">
                <input type="hidden" name="group" value="true">
                <button type="submit" class="default-button default-button-danger">
                    <span class="symbolic symbolic-cross"><?= $this->t('Delete entire series') ?></span>
                </button>
            </form>
        <?php endif; ?>

        <a href="<?= $backUrl ?>" class="default-button default-button-outline"><?= $this->t('No, go back') ?></a>
    </div>
</div>
