<?php

if ($this->event) {
    $eid = $this->event->need('eid');
} else {
    $eid = null;
}

$this->setup(array(
    'title' => 'Event-Administration',
    'panel' => 'centered-panel',
    'back' => array(
        'Event-Administration' => $this->url('backend/event'),
    ),
    'links' => array(
        'User-Administration' => $this->url('backend/user'),
        'Booking-Administration' => $this->url('backend/booking'),
        'Configuration' => $this->url('backend/config'),
    ),
));

$this->headScript()->appendFile($this->basePath('js/tinymce/tinymce.min.js'));
$this->headScript()->appendFile($this->basePath('js/tinymce/tinymce.setup.medium.js'));

?>

<div>
    <h1><?= $this->t('Event-Administration') ?></h1>

    <div class="separator-small"></div>

    <?= $this->backendInfo('i18n') ?>

    <div class="separator separator-line"></div>

    <div class="py-3">
        <?php

        $form = $this->editForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('backend/event/edit', ['eid' => $eid]));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <?= $this->formRowDefault($form, 'ef-name') ?>
        <?= $this->formRowDefault($form, 'ef-description') ?>

        <div class="row">
            <div class="col-md-6">
                <?= $this->formRowDefault($form, 'ef-date-start') ?>
                <?= $this->formRowDefault($form, 'ef-time-start') ?>
            </div>
            <div class="col-md-6">
                <?= $this->formRowDefault($form, 'ef-date-end') ?>
                <?= $this->formRowDefault($form, 'ef-time-end') ?>
            </div>
        </div>

        <?= $this->formRowDefault($form, 'ef-sid') ?>
        <?= $this->formRowDefault($form, 'ef-capacity') ?>
        <?= $this->formRowDefault($form, 'ef-notes') ?>

        <div class="edit-actions">
            <?= $this->formElement($form->get('ef-submit')) ?>

            <?php if ($this->event): ?>
                <a href="<?= $this->url('backend/event/delete', ['eid' => $eid]) ?>" class="default-button default-button-danger">
                    <span class="symbolic symbolic-cross"><?= $this->t('Delete') ?></span>
                </a>
            <?php endif; ?>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>
</div>
