<?php

if (! ($this->dateStart || $this->dateEnd)) {
    $this->dateStart = new DateTime();
    $this->dateEnd = new DateTime();
    $this->dateEnd->modify('+ 2 days');
}

?>

<div class="py-3">
    <form id="esf" name="esf" method="get" action="<?= $this->url('backend/event') ?>">
        <label class="form-label text-muted"><?= $this->t('Date') ?>:</label>
        <div class="d-flex align-items-end flex-wrap gap-2">
            <div class="inline-element">
                <label for="date-start" class="inline-label symbolic symbolic-date"><span><?= $this->t('Date start') ?></span></label>
                <input type="text" name="date-start" id="date-start" value="<?= $this->dateFormat($this->dateStart, IntlDateFormatter::MEDIUM) ?>"
                       class="inline-label-container datepicker form-control form-control-sm" style="padding-left: 28px; width: 110px;">
            </div>

            <span class="text-muted"><?= $this->t('to') ?></span>

            <div class="inline-element">
                <label for="date-end" class="inline-label symbolic symbolic-date"><span><?= $this->t('Date end') ?></span></label>
                <input type="text" name="date-end" id="date-end" value="<?= $this->dateFormat($this->dateEnd, IntlDateFormatter::MEDIUM) ?>"
                       class="inline-label-container datepicker form-control form-control-sm" style="padding-left: 28px; width: 110px;">
            </div>

            <input type="submit" value="<?= $this->t('Search') ?>" class="default-button">
        </div>
    </form>
</div>
