<?php

$this->setup(array(
    'title' => 'Names and text',
    'panel' => 'centered-panel large-sized',
    'back' => array(
        'Configuration' => $this->url('backend/config'),
    ),
));

?>

<div>
    <h1><?= $this->t('Names and text') ?></h1>

    <div class="separator-small"></div>

    <p><?= $this->t('What is the name of your service? What is your name?') ?></p>

    <?= $this->backendInfo('i18n') ?>

    <div class="separator separator-line"></div>

    <div class="py-3">
        <?php

        $form = $this->textForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('backend/config/text'));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <?php foreach (\Backend\Form\Config\TextForm::$definitions as $key => $value): $key = str_replace('.', '_', $key); ?>
            <?php
            if (isset($value[2]) && $value[2]) {
                $type = $value[2];
            } else {
                $type = 'Text';
            }
            ?>

            <?php if ($type == 'Checkbox'): ?>
                <?= $this->formRowCheckbox($form, 'cf-' . $key) ?>
            <?php else: ?>
                <?= $this->formRowDefault($form, 'cf-' . $key) ?>
            <?php endif; ?>
        <?php endforeach; ?>

        <div class="edit-actions">
            <?= $this->formElement($form->get('cf-submit')) ?>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>
</div>
