<?php

if ($this->square) {
    $sid = $this->square->need('sid');
} else {
    $sid = null;
}

$this->setup(array(
    'title' => $this->option('subject.square.type.plural'),
    'panel' => 'centered-panel',
    'back' => array(
        $this->option('subject.square.type.plural') => $this->url('backend/config/square'),
    ),
));

$this->headScript()->appendFile($this->basePath('js/controller/backend/config-square/edit.min.js'));

?>

<div>
    <h1><?= $this->option('subject.square.type.plural') ?></h1>

    <div class="separator-small"></div>

    <p><?= sprintf($this->t('Which %s do you have? What are their names?'), $this->option('subject.square.type.plural')) ?></p>

    <div class="separator separator-line"></div>

    <div class="py-3">
        <?php

        $form = $this->editForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('backend/config/square/edit', ['sid' => $sid]));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <div class="row">
            <div class="col-lg-6">
                <h6 class="text-muted mb-3"><?= $this->t('General') ?></h6>
                <?= $this->formRowDefault($form, 'cf-name') ?>
                <?= $this->formRowDefault($form, 'cf-status') ?>
                <?= $this->formRowDefault($form, 'cf-readonly-message') ?>
                <?= $this->formRowDefault($form, 'cf-priority') ?>
                <?= $this->formRowDefault($form, 'cf-capacity') ?>
                <?= $this->formRowDefault($form, 'cf-capacity-ask-names') ?>
                <?= $this->formRowCheckbox($form, 'cf-capacity-heterogenic') ?>
                <?= $this->formRowCheckbox($form, 'cf-allow-notes') ?>
                <?= $this->formRowDefault($form, 'cf-name-visibility') ?>
            </div>

            <div class="col-lg-6">
                <h6 class="text-muted mb-3"><?= $this->t('Time') ?></h6>
                <?= $this->formRowDefault($form, 'cf-time-start') ?>
                <?= $this->formRowDefault($form, 'cf-time-end') ?>
                <?= $this->formRowDefault($form, 'cf-club-reserved-time-start') ?>
                <?= $this->formRowDefault($form, 'cf-club-reserved-time-end') ?>
                <?= $this->formRowDefault($form, 'cf-time-block') ?>
                <?= $this->formRowDefault($form, 'cf-time-block-bookable') ?>
                <?= $this->formRowCheckbox($form, 'cf-pseudo-time-block-bookable') ?>
                <?= $this->formRowDefault($form, 'cf-time-block-bookable-max') ?>
                <?= $this->formRowDefault($form, 'cf-min-range-book') ?>
                <?= $this->formRowDefault($form, 'cf-range-book') ?>
                <?= $this->formRowDefault($form, 'cf-max-active-bookings') ?>
                <?= $this->formRowDefault($form, 'cf-range-cancel') ?>
                <?= $this->formRowDefault($form, 'cf-label-free') ?>
                <?= $this->formRowDefault($form, 'cf-square-control') ?>
            </div>
        </div>

        <?php if ($this->square): ?>
            <div class="form-check mb-3">
                <input type="checkbox" name="cf-apply-all" value="1" id="cf-apply-all" class="form-check-input">
                <label for="cf-apply-all" class="form-check-label">
                    <?= $this->t('Apply settings to all squares') ?>
                </label>
            </div>
        <?php endif; ?>

        <div class="edit-actions">
            <?= $this->formElement($form->get('cf-submit')) ?>

            <?php if ($this->square): ?>
                <a href="<?= $this->url('backend/config/square/edit/info', ['sid' => $this->square->need('sid')]) ?>" class="default-button default-button-outline">
                    <span class="symbolic symbolic-edit"><?= $this->t('Edit square info and rule texts') ?></span>
                </a>
            <?php endif; ?>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>
</div>
