<?php

if ($this->squareProduct) {
    $spid = $this->squareProduct->need('spid');
} else {
    $spid = null;
}

$this->setup(array(
    'title' => 'Products',
    'panel' => 'centered-panel large-sized',
    'back' => array(
        'Products' => $this->url('backend/config/square/product'),
    ),
));

?>

<div>
    <h1><?= $this->t('Products') ?></h1>

    <div class="separator-small"></div>

    <p><?= $this->t('Which additional products or services do you offer with your bookings?') ?></p>

    <div class="separator separator-line"></div>

    <div class="py-3">

        <?php
        $form = $this->editForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('backend/config/square/product/edit', ['spid' => $spid]));
        $form->prepare();
        ?>

        <?= $this->form()->openTag($form) ?>

        <?= $this->formRowDefault($form, 'cf-name') ?>
        <?= $this->formRowDefault($form, 'cf-description') ?>
        <?= $this->formRowDefault($form, 'cf-options') ?>

        <div class="row">
            <div class="col-md-6">
                <?= $this->formRowDefault($form, 'cf-square') ?>
            </div>
            <div class="col-md-6">
                <?= $this->formRowDefault($form, 'cf-priority') ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <?= $this->formRowDefault($form, 'cf-date-start') ?>
            </div>
            <div class="col-md-6">
                <?= $this->formRowDefault($form, 'cf-date-end') ?>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <?= $this->formRowDefault($form, 'cf-price') ?>
            </div>
            <div class="col-md-4">
                <?= $this->formRowDefault($form, 'cf-gross') ?>
            </div>
            <div class="col-md-4">
                <?= $this->formRowDefault($form, 'cf-rate') ?>
            </div>
        </div>

        <?= $this->formRowDefault($form, 'cf-locale') ?>

        <div class="edit-actions">
            <?= $this->formElement($form->get('cf-submit')) ?>
        </div>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
