<?php

$backUrl = $this->url('backend/config/square/product');

$this->setup(array(
    'title' => 'Delete this product',
    'panel' => 'centered-panel',
    'back' => array(
        'Products' => $backUrl,
    ),
));

?>

<div class="padded centered-text">
    <p><span class="symbolic symbolic-warning"><?= $this->t('Are you sure you want to delete this product?') ?></span></p>

    <div class="edit-actions">
        <a href="<?= $this->url('backend/config/square/product/delete', ['spid' => $this->spid], ['query' => ['confirmed' => 'true']]) ?>" class="default-button default-button-danger">
            <span class="symbolic symbolic-cross"><?= $this->t('Yes, delete this product') ?></span>
        </a>
        <a href="<?= $backUrl ?>" class="default-button default-button-outline"><?= $this->t('No, go back') ?></a>
    </div>
</div>