<?php

$this->setup(array(
    'title' => 'Resend activation email',
    'panel' => 'centered-panel',
    'messages' => array(
        'success' => $this->activationResendMessage,
    ),
    'back' => true,
    'links' => array(
        'Login' => $this->url('user/login'),
    ),
));

?>

<div>
    <h1><?= $this->t('Resend activation email') ?></h1>

    <div class="separator-small"></div>

    <p>
        <?= $this->t('If you did not receive an activation email from us after registration, you can request a new one here.') ?>
        <?= $this->t('Therefore, please type the email adress you used for registration.') ?>
    </p>

    <div class="separator separator-line"></div>

    <div class="py-3">

        <?php

        $form = $this->activationResendForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('user/activation-resend'));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <?= $this->formRowDefault($form, 'arf-email') ?>

        <div class="edit-actions">
            <?= $this->formElement($form->get('arf-submit')) ?>
        </div>

        <?= $this->form()->closeTag() ?>

    </div>
</div>