<?php

$this->setup(array(
    'title' => 'Change password',
    'panel' => 'centered-panel',
    'messages' => array(
        'success' => $this->resetMessage,
    ),
    'back' => true,
    'links' => array(
        'Login' => $this->url('user/login'),
    ),
));

?>

<div>
    <h1><?= $this->t('Change password') ?></h1>

    <div class="separator-small"></div>

    <p>
        <?= $this->t('Now you can type a new password for your user account.') ?>
    </p>

    <hr>

    <div class="py-3" style="max-width: 400px; margin: 0 auto;">

        <?php

        $form = $this->resetForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('user/password-reset', [], ['query' => ['id' => $this->resetUid, 'code' => $this->resetCode]]));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <?= $this->formRowDefault($form, 'prf-pw1') ?>
        <?= $this->formRowDefault($form, 'prf-pw2') ?>
        <?= $this->formRowSubmit($form, 'prf-submit') ?>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
