<?php

$this->setup(array(
    'title' => 'Forgot your password?',
    'panel' => 'centered-panel',
    'messages' => array(
        'success' => $this->passwordMessage,
    ),
    'back' => true,
    'links' => array(
        'Login' => $this->url('user/login'),
    ),
));

?>

<div>
    <h1><?= $this->t('Forgot your password?') ?></h1>

    <div class="separator-small"></div>

    <p>
        <?= $this->t('No need to be sad. You may simply type your email address here and you will soon be able to choose a new password.') ?>
    </p>

    <hr>

    <div class="py-3" style="max-width: 400px; margin: 0 auto;">

        <?php

        $form = $this->passwordForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('user/password'));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <?= $this->formRowDefault($form, 'pf-email') ?>
        <?= $this->formRowSubmit($form, 'pf-submit') ?>

        <?= $this->form()->closeTag() ?>

    </div>
</div>
