<td class="calendar-time-col" style="width: 90px;">
    <?= $this->calendarTimeTable($this->timeStart, $this->timeEnd, $this->timeBlock) ?>
</td>

<?php

$reservations = $this->get('reservations');
$events = $this->get('events');

$reservationsForColPlugin = $this->plugin('CalendarReservationsForCol');
$reservationsCleanupPlugin = $this->plugin('CalendarReservationsCleanup');

$eventsForColPlugin = $this->plugin('CalendarEventsForCol');
$eventsCleanupPlugin = $this->plugin('CalendarEventsCleanup');

/* Loop through day cols */

$walkingDate = clone $this->dateStart;
$walkingIndex = 0;

while ($walkingDate <= $this->dateEnd) {
    if (in_array($walkingDate->format('Y-m-d'), $this->dayExceptions) ||
        in_array($walkingDate->format('l'), $this->dayExceptions)) {

        if (! in_array($walkingDate->format('Y-m-d'), $this->dayExceptionsExceptions)) {
            $walkingDate->modify('+1 day');
            $walkingIndex++;
            continue;
        }
    }

    echo sprintf('<td class="calendar-date-col %s">',
        ($walkingIndex > 0 ? 'responsive-pass-' . (max(1, 6 - $walkingIndex)) : ''));

    echo '<div class="calendar-date-wrapper">';
    echo '<table class="calendar-date-table full-width">';

    echo $this->calendarDateRow($walkingDate, $this->squaresCount);
    echo $this->calendarSquareRow($this->squares, $this->squaresCount);

    /* Update square opening times for this specific date */

    foreach ($this->squares as $sq) {
        $ot = $this->openingTimesManager->getOpeningTimes($walkingDate, $sq->need('sid'));
        if ($ot) {
            $parts = explode(':', $ot['time_start']);
            $sq->setExtra('time_start_sec', $parts[0] * 3600 + $parts[1] * 60);
            $parts = explode(':', $ot['time_end']);
            $sq->setExtra('time_end_sec', $parts[0] * 3600 + $parts[1] * 60);
        } else {
            $parts = explode(':', $sq->need('time_start'));
            $sq->setExtra('time_start_sec', $parts[0] * 3600 + $parts[1] * 60);
            $parts = explode(':', $sq->need('time_end'));
            $sq->setExtra('time_end_sec', $parts[0] * 3600 + $parts[1] * 60);
        }
    }

    /* Loop through time rows */

    for ($walkingTime = $this->timeStart; $walkingTime < $this->timeEnd; $walkingTime += $this->timeBlock) {
        echo '<tr class="calendar-core-row">';

        $walkingDate->modify('+' . $walkingTime . ' sec');

        $reservationsForCol = $reservationsForColPlugin($reservations, $walkingDate, $walkingTime, $this->timeBlock);
        $eventsForCol = $eventsForColPlugin($events, $walkingDate, $walkingTime, $this->timeBlock);

        /* Loop through square cells */

        foreach ($this->squares as $square) {
            echo $this->calendarCellLogic($walkingDate, $walkingTime, $this->timeBlock, $this->dateNow,
                $square, $this->user, $reservationsForCol, $eventsForCol);
        }

        $walkingDate->setTime(0, 0, 0);

        echo '</tr>';
    }

    $reservationsCleanupPlugin($reservations, $walkingDate);
    $eventsCleanupPlugin($events, $walkingDate);

    echo $this->calendarSquareRow($this->squares, $this->squaresCount, 'no-print');
    echo $this->calendarDateRow($walkingDate, $this->squaresCount, 'no-print');

    echo '</table>';
    echo '</div>';

    echo '</td>';

    $walkingDate->modify('+1 day');
    $walkingIndex++;
}
