<?php

$this->setup(array(
    'title' => $this->t('Square control'),
    'panel' => 'centered-panel large-sized',
    'back' => array(
        'Configuration' => $this->url('backend'),
    ),
));

?>

<div>
    <h1><?= $this->t('Square control') ?></h1>

    <div class="separator-small"></div>

    <p><?= sprintf($this->t('Which inactive DoorCodes do you have? You may want to remove them?'), $this->t('Door codes')) ?></p>

    <div class="separator separator-line"></div>

    <div class="py-3">

        <?php if ($this->codes): ?>
            <?= $this->backendDoorCodesFormat($this->codes) ?>
        <?php endif; ?>

        <div class="centered-text mt-4">
            <a href="<?= $this->url('backend/squarecontrol/removeinactivedoorcodes') ?>" class="default-button default-button-danger">
                 <span class="symbolic symbolic-cross"><?= sprintf($this->t('Remove all inactive codes'), $this->t('Door codes')) ?></span>
            </a>
        </div>

    </div>
</div>
