<?php

if ($this->user) {
    $uid = $this->user->need('uid');
} else {
    $uid = null;
}

if ($this->search) {
    $back = array(
        'User-Administration' => $this->url('backend/user', [], ['query' => ['usf-search' => $this->search]])
    );
} else {
    $back = true;
}

$this->setup(array(
    'title' => 'User-Administration',
    'panel' => 'centered-panel large-sized',
    'back' => $back,
    'links' => array(
        'Booking-Administration' => $this->url('backend/booking'),
        'Event-Administration' => $this->url('backend/event'),
        'Configuration' => $this->url('backend/config'),
    ),
));

$this->headScript()->appendFile($this->basePath('js/controller/backend/user/edit.min.js'));

?>

<div>
    <h1><?= $this->t('User-Administration') ?></h1>

    <div class="separator-small"></div>

    <p><?= $this->t('Here you can create, edit or delete the users of your system.') ?></p>

    <hr>

    <?= $this->partial('backend/user/index.search.phtml', ['search' => $this->search]) ?>

    <hr>

    <div class="py-3">

        <?php

        $form = $this->editUserForm;
        $form->setAttribute('method', 'post');
        $form->setAttribute('action', $this->url('backend/user/edit', ['uid' => $uid], ['query' => ['search' => $this->search]]));
        $form->prepare();

        ?>

        <?= $this->form()->openTag($form) ?>

        <?php if ($form->getMessages()): ?>
            <div class="alert alert-danger" role="alert">
                <strong><?= $this->t('Please check your input') ?></strong>
            </div>
        <?php endif; ?>

        <div class="row">
            <div class="col-lg-6 mb-4">
                <div class="text-center mb-3">
                    <span class="legacy-badge">1</span> <span class="legacy-badge-label"><?= $this->t('Account data') ?></span>
                </div>

                <?= $this->formRowDefault($form, 'euf-uid') ?>
                <?= $this->formRowDefault($form, 'euf-alias') ?>
                <?= $this->formRowDefault($form, 'euf-status') ?>
                <?= $this->formRowDefault($form, 'euf-privileges') ?>
                <?= $this->formRowDefault($form, 'euf-email') ?>
                <?= $this->formRowDefault($form, 'euf-pw') ?>

                <div class="mb-3">
                    <label class="form-label"><?= $this->t('Last activity: ') ?></label>
                    <div>
                        <?php
                        if ($this->user && $this->user->get('last_activity')) {
                            echo $this->prettyDate(new \DateTime($this->user->need('last_activity')));
                        } else {
                            echo '-';
                        }
                        ?>
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label"><?= $this->t('Last IP: ') ?></label>
                    <div>
                        <?php
                        if ($this->user && $this->user->get('last_ip')) {
                            echo $this->user->get('last_ip');
                        } else {
                            echo '-';
                        }
                        ?>
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label"><?= $this->t('Created: ') ?></label>
                    <div>
                        <?php
                        if ($this->user && $this->user->get('created')) {
                            echo $this->prettyDate(new \DateTime($this->user->need('created')));
                        } else {
                            echo '-';
                        }
                        ?>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 mb-4">
                <div class="text-center mb-3">
                    <span class="legacy-badge">2</span> <span class="legacy-badge-label"><?= $this->t('Personal data') ?></span>
                </div>

                <div class="mb-3">
                    <label class="form-label"><?= $this->formLabel($form->get('euf-gender')) ?></label>
                    <div>
                        <?= $this->formElement($form->get('euf-gender')) ?>
                        <?= $this->formElementErrors($form->get('euf-gender')) ?>
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label"><?= $this->formLabel($form->get('euf-firstname')) ?></label>
                    <div>
                        <?= $this->formElement($form->get('euf-firstname')) ?>
                        <?= $this->formElement($form->get('euf-lastname')) ?>
                        <?= $this->formElementErrors($form->get('euf-firstname')) ?>
                        <?= $this->formElementErrors($form->get('euf-lastname')) ?>
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label"><?= $this->formLabel($form->get('euf-street')) ?></label>
                    <div>
                        <?= $this->formElement($form->get('euf-street')) ?>
                        <?= $this->formElementErrors($form->get('euf-street')) ?>
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label"><?= $this->formLabel($form->get('euf-zip')) ?></label>
                    <div>
                        <?= $this->formElement($form->get('euf-zip')) ?>
                        <?= $this->formElement($form->get('euf-city')) ?>
                        <?= $this->formElementErrors($form->get('euf-zip')) ?>
                        <?= $this->formElementErrors($form->get('euf-city')) ?>
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label"><?= $this->formLabel($form->get('euf-phone')) ?></label>
                    <div>
                        <?= $this->formElement($form->get('euf-phone')) ?>
                        <?= $this->formElementErrors($form->get('euf-phone')) ?>
                    </div>
                </div>
                <div class="mb-3">
                    <label class="form-label"><?= $this->formLabel($form->get('euf-member')) ?></label>
                    <div>
                        <?= $this->formElement($form->get('euf-member')) ?>
                        <?= $this->formElementNotes($form->get('euf-member')) ?>
                        <?= $this->formElementErrors($form->get('euf-member')) ?>
                    </div>
                </div>
                <?= $this->formRowDefault($form, 'euf-budget') ?>
                <div class="mb-3">
                    <label class="form-label"><?= $this->formLabel($form->get('euf-notes')) ?></label>
                    <div>
                        <?= $this->formElement($form->get('euf-notes')) ?>
                        <?= $this->formElementNotes($form->get('euf-notes')) ?>
                        <?= $this->formElementErrors($form->get('euf-notes')) ?>
                    </div>
                </div>
            </div>
        </div>

        <hr>

        <div class="text-center">
            <div id="euf-generic-label" style="display: none;"><?= $this->t('Name') ?></div>

            <?= $this->formElement($form->get('euf-submit')) ?>

            <?php if ($this->user): ?>
                &nbsp;
                <a href="<?= $this->url('backend/user/delete', ['uid' => $uid], ['query' => ['search' => $this->search]]) ?>" class="btn btn-outline-danger">
                    <span class="fa fa-times"></span> <?= $this->t('Delete user') ?>
                </a>
            <?php endif; ?>
        </div>

        <?= $this->form()->closeTag() ?>
    </div>
</div>
