<?php

$this->setup(array(
    'title' => 'Administration',
    'panel' => 'centered-panel',
    'back' => true,
));

?>

<div>
    <h1 class="no-ajax mb-3"><?= $this->t('Administration') ?></h1>

    <div class="list-group">
        <a href="<?= $this->url('backend/user') ?>" class="list-group-item list-group-item-action d-flex align-items-center">
            <span class="symbolic symbolic-user me-3 fs-5"><?= $this->t('Users') ?></span>
            <span class="text-muted small ms-auto d-none d-md-inline"><?= $this->t('Create, edit or delete the users of your system') ?></span>
        </a>
        <a href="<?= $this->url('backend/user/stats') ?>" class="list-group-item list-group-item-action ps-5 small">
            <span class="symbolic symbolic-stats"><?= $this->t('Statistic') ?></span>
        </a>

        <a href="<?= $this->url('backend/booking') ?>" class="list-group-item list-group-item-action d-flex align-items-center">
            <span class="symbolic symbolic-booking me-3 fs-5"><?= $this->t('Bookings') ?></span>
            <span class="text-muted small ms-auto d-none d-md-inline"><?= $this->t('Create, edit or delete the bookings of your system') ?></span>
        </a>
        <a href="<?= $this->url('backend/booking/stats') ?>" class="list-group-item list-group-item-action ps-5 small">
            <span class="symbolic symbolic-stats"><?= $this->t('Statistic') ?></span>
        </a>

        <a href="<?= $this->url('backend/squarecontrol') ?>" class="list-group-item list-group-item-action d-flex align-items-center">
            <span class="symbolic symbolic-booking me-3 fs-5"><?= $this->t('Square control') ?></span>
            <span class="text-muted small ms-auto d-none d-md-inline"><?= $this->t('Delete the inactive door codes of your system') ?></span>
        </a>

        <a href="<?= $this->url('backend/event') ?>" class="list-group-item list-group-item-action d-flex align-items-center">
            <span class="symbolic symbolic-date me-3 fs-5"><?= $this->t('Events') ?></span>
            <span class="text-muted small ms-auto d-none d-md-inline"><?= $this->t('Create, edit or delete the events of your system') ?></span>
        </a>
        <a href="<?= $this->url('backend/event/stats') ?>" class="list-group-item list-group-item-action ps-5 small">
            <span class="symbolic symbolic-stats"><?= $this->t('Statistic') ?></span>
        </a>

        <a href="<?= $this->url('backend/config') ?>" class="list-group-item list-group-item-action d-flex align-items-center">
            <span class="symbolic symbolic-config me-3 fs-5"><?= $this->t('Configuration') ?></span>
            <span class="text-muted small ms-auto d-none d-md-inline"><?= $this->t('Configure your system just as you need it') ?></span>
        </a>
    </div>
</div>
