<div class="d-flex flex-wrap align-items-center justify-content-center gap-2">
    <span>
        <?php
        echo sprintf($this->t('To book %s, %splease register first%s'),
            $this->option('subject.square.type.plural'),
            '<a href="' . $this->url('user/registration') . '" class="btn btn-sm btn-primary">', '</a>');
        ?>
    </span>

    <a href="<?= $this->url('user/login') ?>" class="btn btn-outline-primary btn-sm d-lg-none">
        <span class="fa fa-sign-in"></span> <?= $this->t('Login') ?>
    </a>

    <a href="<?= $this->url('service/help') ?>" class="btn btn-outline-secondary btn-sm" data-tooltip="<?= sprintf($this->t('Get additional %shelp and information%s'), '<b>', '</b>') ?>">
        <b>?</b>
    </a>
</div>

<form method="post" action="<?= $this->url('user/login') ?>" class="d-none d-lg-block mt-2">
    <div class="d-flex align-items-center gap-2">
        <span class="text-muted"><?= $this->t('or simply login here') ?></span>

        <input type="text" name="lf-email" id="lf-email" value=""
            class="form-control form-control-sm" style="max-width: 200px;" placeholder="<?= $this->t('Email address') ?>">

        <input type="password" name="lf-pw" id="lf-pw" value=""
            class="form-control form-control-sm" style="max-width: 160px;" placeholder="<?= $this->t('Password') ?>">

        <input type="submit" value="<?= $this->t('Login') ?>" class="btn btn-primary btn-sm text-nowrap">
    </div>
</form>
